FROM python:latest
ADD requirements.txt bdd_datascientest_projet3.db api.py ./
RUN pip install --no-cache-dir --upgrade pip && pip install --no-cache-dir requests && pip install -r requirements.txt

#RUN pip install --no-cache-dir --upgrade pip && \
#    pip install --no-cache-dir requests && \
#    pip install -r requirements.txt

EXPOSE 5010

CMD python3 api.py